LICENSE.md
README.md

This brings us into what I think is compliance with thoughtbot's MIT license.
Fixes #1.

Update license to include thoughtbot's MIT license

---

README.md
mac

Since `virtualenvwrapper` requires sourcing before the `mkvirtualenv` command
can be used, this now makes 2 commands that need to be sourced after the
script ends. RVM is the other one.
Instead of making the installation command even longer, I've opted to add
instructions to quit and relaunch Terminal after the script ends.
Closes #2 and #3.

Add python3 and virtualenvwrapper.

---

mac

Up until version 1.26.11, RVM installed bundler by default, but now it doesn't anymore. However, RVM still comes with `rubygems-bundler` and `bundler-unload`, and running `gem list bundler --installed` while those gems are present will return true, erroneously leading the `gem_install_or_update` function to believe that bundler was already installed.
By using a regular expression, we look for a gem name that starts with bundler, followed by a space and an opening parenthesis, which will properly detect whether or not bundler is installed.
Also includes shellcheck fixes to make the tests pass.
Closes #12.

Improve check for bundler presence.

---

mac

RVM stopped shipping with Bundler, which means that if you clone
a repo that uses a `.ruby-gemset`, or if you install a new version
of Ruby, or update to a new version of RVM, Bundler won't be
automatically available, and `bundle install` will fail.
Beginners might not know they can `gem install bundler` to fix the
issue, and even if you did know, having to type that each time is
annoying. Since Bundler is widely used, it makes sense to install
it in the global gemset so that it is available at any time.
RVM provides the  `--with-gems` flag that can be used to install
bundler when installing RVM for the first time, and when updating
RVM. However, there is a bug where using the flag when installing
for the first time will prevent Ruby from being installed.
Therefore, I only enabled the …

Install Bundler globally

---

README.md
mac

Why:
The original reason for including Qt was to provide support for Ruby apps that are using capybara-webkit. However, capybara-webkit will soon require Qt5 to be installed, but Qt5 requires the full Xcode package.
I don't think it's possible to automate the installation of Xcode, and even if it were possible, I wouldn't want to force everyone to download a multi-gigabyte file. Instead, it makes more sense to recommend PhantomJS and Poltergeist (for Ruby apps), which works just as well as capybara-webkit.

Replace Qt with PhantomJS

---

mac

Before, the script would determine whether or not to launch GitHub based on the presence of `github_rsa.pub`. This isn't robust since some users might have a GitHub SSH key with a different name, or might not have one even though GitHub app is installed.
The script then tries to launch GitHub app from `~/Applications`, but if the user already has the app in `/Applications`, Brew Cask will not have installed it in `~/Applications`, causing the script to report a failure at the end since it can't find the app.
Instead, we first check to see if the user already has GitHub installed in the `/Applications` directory. If they do, we assume they already set up their keys, and echo a helpful message. Otherwise, that means GitHub was installed via Brew Cask and can be launched without issues. …

Only launch GitHub app if not previously installed

---

.travis.yml

The old apt-repository is no longer available so we need to update it to one that provides shellcheck.
I also updated the sudo command to use passwordless mode per the Travis documentation:
http://docs.travis-ci.com/user/customizing-the-build/#Installing-Packages-Using-apt

Update travis config for shellcheck

---

mac

The name has changed in the Cask repository: http://caskroom.io/search

Rename github cask to github-desktop

---

mac

The GitHub app for Mac has been renamed "GitHub Desktop.app", which explains why the Cask name was updated. This fix allows the app to be launched when necessary.

Rename GitHub to GitHub Desktop

---

README.md
mac

PhantomJS is not yet supported on El Capitan. Therefore, we detect if El Capitan is running, and if not, then we can safely install PhantomJS.
Closes #30.

Skip phantomjs on El Capitan

---

README.md
mac

This will use n, which is a bit simpler to use than nvm, to allow folks to manage node versions. This forgoes installing node/npm directly with homebrew.

Use n to manage node.js/npm versions

---

README.md
mac

This changeset adds some additional support around installing Node.js and Python and updates the README accordingly.  First, it adds in a bit more backward compatibility support so that if you originally installed Node.js or Python 3.x with the script, you will still receive updates with Homebrew.  The following additional changes are also added:
- Node.js:  A check for nvm is in place, and if it is found the rest of the Node.js install/update processing is skipped since we assume you are managing it yourself.
- Python 3.x:  A check for pyenv now exists; if it Python 3.x is not installed yet and neither is pyenv, pyenv is now installed prior to installing Python 3.x.
- Python 3.x:  A check for the pyenv virtualenvwrapper plugin is now in place as well before installing virtualenvwrapper …

Update Node.js and Python installation pieces

---

mac

Pivotal's CLI version sometimes lags the community version, which is what we prefer people use in any case to avoid any implicit dependency on a commercial vendor.

Prefer community Cloud Foundry release over Pivotal's

---

mac

**Why**: To make sure the system is ready to brew before installing or upgrading tools. This can catch errors due to upgrading OS X when Homebrew had previously been installed, for example.

Run `brew doctor` after `brew update`

---

mac

The latest cf-cli release is resulting in a SHA1 mismatch error. This change allows the script to continue running if cf-cli failed to install, and asks the user to report the issue on GitHub.
Fixes #45.

Skip failed cf-cli installation

---

.about.yml

Questions? You can read more about the spec here: https://github.com/18F/about_yml
Is this pull incorrect? File an issue at https://github.com/sharms/meta-machine

.about.yml is invalid - set owner_type: project

---

README.md
mac

Removed extra lines now that the [linked homebrew issue](https://github.com/Homebrew/homebrew/issues/42249) has been resolved.

Prune phantomjs lines - install bug has been fixed

---

.laptop.local
Brewfile
README.md
mac

**Why**:
Homebrew-bundle does what the custom functions used to do. It also allows us to
use a Brewfile, which makes it easier to see in one place what gets installed,
and makes it easier to customize that list.
As part of moving to a Brewfile, I also removed the directives to restart
Redis, Postgres, and MySQL. Given that the script installs Homebrew services,
managing services manually is very easy, and the user can choose when to start
them.

Use `brew bundle` instead of custom functions

---

Brewfile
README.md

**Why**: Several vulnerabilities have been reported.
See https://imagetragick.com/.

Remove ImageMagick from main Brewfile

---

mac

Before, we were using both `sed` and `egrep` to return all matches that follow the pattern 3.x.y. We only need the first match. Otherwise, `pyenv install [match]` will fail. We also don't need `sed` here since we're not replacing anything. We just want the first match, which should be the stable build version number.
Closes #58.

Fix Python stable build number extraction

---

mac

**Why**: If a git secrets config is already present, running a `git secrets` command will exit with status 1, preventing the laptop script from executing the rest of the script.
**How**: Add `|| true` to the end of all `git secrets` commands (except the first one that installs git secrets). See: https://github.com/awslabs/git-secrets/issues/24

Allow git secrets commands to be run many times

---

mac

**Why**: It’s not ready for prime time yet.
- We need to make sure the regexes don’t flag common false positives
- We need to figure out the best way to incorporate configuration files while making the sure the user has those files locally. Currently, the script assumes the user has the `secret-patterns` folder, but because they install the script by only downloading the `mac` and `Brewfile` files via curl, they don’t have the folder. We need to determine if it makes sense to have the user download every file the script needs, or if they should clone the repo instead.

Temporarily disable git-secrets

---

README.md
mac

As the front end guild standardized it here: https://pages.18f.gov/frontend/#install-npm. It was standardized over `n` because it doesn't require sudo to install global packages.

Install nvm instead of n

---

seekrets-install

This PR enables downloading and enabling of rulesets in the seekrets-install script.

Seekrets install - download and enable rulesets

---

mac

**Why**: The previous PR that replaced `n` with `nvm` was not properly tested and caused the script to fail
**How**:
- load nvm inside the script so that the `nvm` command can be used
- add `node` to the `nvm install` command because it requires a default version to be set

Fix nvm installation

---

README.md
mac
seekrets-install

Small cleanup of some final issues:
- use `mktemp` for our work dir, which prevents race conditions
- Actually update the README as appropriate
- clean up how `mac` calls the `seekrets-install` in same way user would from README
- Hide various output that is just noise by redirecting to `/dev/null`
/cc @alain-hoang

General cleanup of git seekrets

---

test/test_helper.bash

When we're testing things, we shouldn't rely on the installation but rather we should rely on what we're committing locally.

Insure that tests are using the local repo

---

seekret-rules/mandrill.rule

When writing the documentation for contributing and developing rulesets for git-seekret we found that the mandrill properties were a bit redundant.
cc: @alain-hoang

Rename properties to not contain rule name

---

seekrets-install

Secret rules should be coming from within the repository itself and shouldn't be hard-coded. This will allow for a shorter feedback loop for local development and came up during the Git Seekret documentation #116
cc: @alain-hoang

Use files in `seekret-rules` to determine defaults

---

README.md
mac

**Why**: To provide an easy way to refer back to the instructions
without having to run the script.
Also, moved the note about being able to switch back to before the shell
is changed.

Add change shell instructions to README

---

mac

**Why**: Sometimes, `brew update` doesn’t actually get the latest commit from the repo due to a known issue with Homebrew. We want to make sure we have the latest commit from Homebrew/brew because it fixes a nasty bug where existing Mac apps that the script attempts to install are removed. See: https://github.com/Homebrew/brew/issues/1785

Force fetch latest Homebrew

---

README.md
laptop
mac

**Why**: To reduce the installation from three commands to one, and to
make it easy to repeatedly run the script via a shell alias, since it
is recommended to do so to keep your computer up to date.

Simplify installation instructions and add alias

---

.travis.yml
circle.yml
seekrets-install
test/seekrets.bats
test/test_helper.bash

**Why**:
- It’s super slow
- It’s not a clean OS X image. It comes with a bunch of stuff like XCode, Homebrew, RVM, and other settings we might not want, or things we’re not aware of that can interfere with the script.
- None of the bugs we’ve found have been the result of the script failing on Travis.
- It’s more reliable to test changes manually or by having many people use the script and report issues. I also have a spare laptop where I can erase the hard drive and install macOS from scratch.

Don’t use OS X image for Travis

---

mac

**Why**: Due to the new way of installing the script via curl and piping to `sh`, it doesn’t see the `Brewfile`, so we must explicitly specify its path.

Specify Brewfile path

---

Brewfile
mac

**Why**:
- We were assuming `caskroom/versions` would be present if `brew-cask` was installed, but that’s not a safe assumption to make.
- tapping `caskroom/cask` and `caskroom/versions` is no longer necessary in Brewfile
Fixes #133.

Clean up code around Homebrew Casks

---

.laptop.local
Brewfile.local
README.md
mac

**Why**: To make it easier to manage a local Brewfile, and to allow adding logic in case `brew bundle` fails, which permits the script to continue running rather than exiting.

Improve customization options

---

README.md
mac

Since the `mac` script involves reading from user input, we can't
pipe the curl command to `sh` or `bash` because we would be asking
bash to read from both a file and STDIN.
The solution is to use redirection of STDIN
See: http://unix.stackexchange.com/a/247221

Fix installation command.

---

seekrets-install

Using `-L`  to have curl follow redirects to AWS rather than parsing the url out of HTML should make this less prone to breakage.

Simplify downloading the git-seekret binary

---

seekret-rules/slack.rule
seekrets-install
test/seekrets.bats
test/test_helper.bash

Slack API tokens, conveniently, always start with `xox*`, so identifying them is pretty easy.  They then have 11 digits, 12 digits, 12 digits, and 32 alphanumeric characters (they look like hex characters but I'm not sure, so I tested for a-z, 0-9).

Add seekret rule for Slack API tokens

---

mac

These commands appear to have been put into resolve a long-fixed homebrew bug. In some cases,  they may break the homebrew git repo link, and in any case they should not be needed.

Removed unnecessary git commands

---

.laptop.local
Brewfile.local
README.md
seekrets-install

- adds `oh-my-zsh` install to `.laptop.local` but comments it out (closes #32)
- adds GNU coreutils to `Brewfile.local` but comments it out (closes #36)
- adds a note in the README about updating git on older versions of Ubuntu before installing git-seekret (closes #136)
- fixes a tool version check bug (closes #141)

A variety of changes to address longstanding issues

---

mac

The command `nvm install node --lts` installs the latest version of Node.js, not the latest LTS version.  To fix, remove `node`.  This seems to be a change in the behavior of nvm.
Additionally, the `mac` script is configured to exit if any command within it exits with a non-zero code.  However, `nvm` is itself a bash script that has commands that have non-zero exit codes that are NOT exceptional.  That is, a successful `nvm install` may include some commands exiting with non-zero statuses.  To handle that, this PR also disables the "exit if anything is non-zero" when it runs `nvm` and re-enables it afterwards.
Closes #166

Fix nvm LTS install

---

mac

Adds support for using fish as the developer shell (#164).
Changes from the zsh/bash setup:
* `rbenv` for ruby version management.
Rough edges:
* `nvm` is installed, but doesn't work in fish without a wrapper. A link to a potential wrapper is provided during the run.

Add Fish shell support

---

mac

Accidentally put bash process substitution syntax into the fish alias.

Fix laptop alias syntax for fish shell

---

README.md

WHY: caskroom.io now is parked with an advertisement.

Cask website is no longer active.

---

.circleci/config.yml

We've procured a MacOS plan on CircleCI, so this enabled testing for the seekrets script as well as the laptop/mac script.
Please double check that this [script output](https://circleci.com/gh/18F/laptop/124) looks correct. CI runs the script and asserts it exits 0. Is that sufficient?

Enable MacOS and laptop script testing in CI

---

README.md
seekrets-install

Instead of hard-coding the list of rules (which requires authors of new rules to remember to update the install script), have the script query the Github API for the list of rules.
Closes #142

Fetch list of git-seekret rules from Github

---

mac

Starting with macOS 10.14, the path to standard header file has been moved.  The build tools bundled with the macOS SDK look for headers in the new path, but 3rd-party build tools continue to look for the files in the standard paths.  That includes `pyenv`, which now fails to build because it can't find zlib headers.
[relevant pyenv issue](https://github.com/pyenv/pyenv/issues/1219)
[Xcode 10 release notes](https://developer.apple.com/documentation/xcode_release_notes/xcode_10_release_notes)
Rather than hack in the paths to the headers based on the OS version, this PR installs zlib with brew and links to that for building with pyenv.
Closes #180

Use zlib from brew for building Python

---

mac

I also removed `app_is_installed` function.
1) it's not used anywhere
2) I think it was broken, since it reported that Github was installed on my refreshed Macbook even though it isn't.

Remove check for Github desktop from mac script

---

Brewfile
README.md

Removing CloudApp from the Brewfile and README.md. The download fails when connected to the VPN because [http://getcloudapp.com](http://getcloudapp.com) is now blocked. No longer approved software?

Remove cloudapp since blocked on VPN.

---

mac

Per attempting to install via ruby:
```
Warning: The Ruby Homebrew installer is now deprecated and has been rewritten in
Bash. Please migrate to the following command:
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
```

Update to bash-based Homebrew install

---

mac

Eliminates a warning triggered by the brew tap command being passed an argument of "-1".  Note: this should result in the following lines working again, which will now uninstall caskroom/versions for anyone who already has it installed and reruns the script.
Someone with a little more familiarity than me could better judge whether we want to do that or whether we'd rather delete these lines:
```
if tap_is_installed 'caskroom/versions'; then
brew untap caskroom/versions
fi
```

Remove invalid option for brew tap
